version: '3'

services:
  db-rails:
    image: mysql:8.0
    volumes:
      - mysql_data_rails:/var/lib/mysql
      - type: bind
        source: "./docker/mysql/my.cnf"
        target: "/etc/mysql/conf.d/my.cnf"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    ports:
      - ${DB_PORT}:3306
    command: >
      bash -c "mkdir -p /var/log/mysql
      && chown -hR mysql:mysql /var/log/mysql
      && /entrypoint.sh mysqld"
    restart: unless-stopped

  web-rails:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myHome/
    ports:
      - 3000:3000
    depends_on:
      - db-rails

volumes:
  mysql_data_rails: